name: jobs examples

on:
   push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: example of invalid command
        run: echo Hello, world! Build failed.


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: step do job2
        run: echo Hello, world! Job2.
