name: scheduled event

on:
  schedule:
    - cron: '*/3 * * * 1,3'


jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule === '*/3 * * * 1,3'
        run: echo "This step will run on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
